service: sl-manager-api

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region,'us-east-1'}
  stage: ${opt:stage, 'local'}
  logs:
    restApi:
      accessLogging: true
      executionLogging: false
      format: '{"requestId": "$context.requestId", "ip": "$context.identity.sourceIp", "caller": "$context.identity.caller", "user": "$context.identity.user", "requestTime": "$context.requestTime", "httpMethod": "$context.httpMethod", "resourcePath": "$context.resourcePath", "status": "$context.status", "protocol": "$context.protocol", "responseLength": "$context.responseLength"}'
  memorySize: 1024 # optional, in MB, default is 1024
  environment:
    STAGE: ${opt:stage, 'local'}
    REGION: ${opt:region, 'us-east-1'}

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: get
          path: /api
  products:
    handler: src/lambda.handler
    events:
      - http:
          method: get
          path: /api/products
          cors: true
  productsByProvider:
    handler: src/lambda.handler
    events:
      - http:
          method: get
          path: /api/products/{provider}
          cors: true
  productsUpload:
    handler: src/lambda.handler
    events:
      - http:
          method: post
          path: /api/products/{provider}/upload
          cors: true
  users:
    handler: src/lambda.handler
    events:
      - http:
          method: get
          path: /api/users
          cors: true

custom:
  serverless-offline:
    host: '0.0.0.0'
    noPrependStageInUrl: true
    httpPort: 5002
    # lambdaPort: 5011
    prune:
      automatic: true
      number: 10
