service: ls-manager-backend

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'local'}
  logs:
    restApi:
      accessLogging: true
      executionLogging: false
      format: '{"requestId": "$context.requestId", "ip": "$context.identity.sourceIp", "caller": "$context.identity.caller", "user": "$context.identity.user", "requestTime": "$context.requestTime", "httpMethod": "$context.httpMethod", "resourcePath": "$context.resourcePath", "status": "$context.status", "protocol": "$context.protocol", "responseLength": "$context.responseLength"}'
  memorySize: 2048 # optional, in MB, default is 1024
  environment:
    STAGE: 'local'
    REGION: 'us-east-1'

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: get
          path: /products

      - http:
          method: post
          path: /products/{provider}/upload

custom:
  serverless-offline:
    noPrependStageInUrl: true
